### ISSUE TITLE
Configure the name of the connection to rabbitMQ

### ISSUE THREAD

**Issue by genoher** [cocosip/sharp-abp#39]
I would like to be able to specify the name of the connection, is it possible, if so, how is it configured? 
Now in rabbit mq is showing the name of the applicacion.

with abp and sharp-abp I am using like that...
```
    public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        this.PreConfigure((Action<AbpMassTransitRabbitMqOptions>)(options =>
        {            
            options.Consumers.Add(new RabbitMqConsumerConfiguration()
            {
                ExchangeName = RabbitMqQueues.ExchangeOrderStateChanged,

                QueueName = RabbitMqQueues.QueueOrderStateChanged,

                Configure = new Action<IBusRegistrationConfigurator>(c =>
                {
                    c.AddConsumer<OrderStateChangedConsumer>();
                }),

                MessageConfigure = new Action<string, IRabbitMqBusFactoryConfigurator>((exchangeName, c) =>
                {
                    c.Message<OrderStateChanged>(e =>
                    {
                        e.SetEntityName(exchangeName);
                    });
                }),

                ReceiveEndpoint = new Action<string, string, Action<string, string, IRabbitMqReceiveEndpointConfigurator>, IBusRegistrationContext, IRabbitMqBusFactoryConfigurator>((exchangeName, queueName, preConfigure, ctx, cfg) =>
                {
                    cfg.ReceiveEndpoint(queueName, e =>
                    {
                        preConfigure?.Invoke(exchangeName, queueName, e);
                        e.ConfigureConsumer<OrderStateChangedConsumer>(ctx);
                    });
                })
            });

            Serilog.Log.Information($"    - PreConfigure AbpMassTransitRabbitMqOptions ExchangeName => {RabbitMqQueues.ExchangeOrderStateChanged}, with QueueName => {RabbitMqQueues.QueueOrderStateChanged}, with Consumer => {nameof(OrderStateChangedConsumer)}, with Message => {nameof(OrderStateChanged)}");

        }));
        Serilog.Log.Debug(" - PreConfigure Services AbpMassTransitRabbitMqOptions.");
    }
```

In another applicacion, i configured the connection name like that... is a very old version of the library Masstransit 5.5.6.0

```
                    _bus = MassTransit.Bus.Factory.CreateUsingRabbitMq(x =>
                    {
                        x.UseLog4Net();

                        //// IRabbitMqHost host = x.Host(new Uri(rabbitMqHostUri), connectionName, h =>                        
                        x.Host(new Uri(rabbitMqHostUri), connectionName, h =>
                        {
                            h.Username(rabbitMqHostUsername);
                            h.Password(rabbitMqHostPassword);                            
                        });
                        ....
```

Thank you very much, it has made my use of masstransit / rabbitmq with abp much faster.

**Comment by cocosip** [comment]
> I would like to be able to specify the name of the connection, is it possible, if so, how is it configured? Now in rabbit mq is showing the name of the applicacion.
> 
> with abp and sharp-abp I am using like that...
> 
> ```
>     public override void PreConfigureServices(ServiceConfigurationContext context)
>     {
>         this.PreConfigure((Action<AbpMassTransitRabbitMqOptions>)(options =>
>         {            
>             options.Consumers.Add(new RabbitMqConsumerConfiguration()
>             {
>                 ExchangeName = RabbitMqQueues.ExchangeOrderStateChanged,
> 
>                 QueueName = RabbitMqQueues.QueueOrderStateChanged,
> 
>                 Configure = new Action<IBusRegistrationConfigurator>(c =>
>                 {
>                     c.AddConsumer<OrderStateChangedConsumer>();
>                 }),
> 
>                 MessageConfigure = new Action<string, IRabbitMqBusFactoryConfigurator>((exchangeName, c) =>
>                 {
>                     c.Message<OrderStateChanged>(e =>
>                     {
>                         e.SetEntityName(exchangeName);
>                     });
>                 }),
> 
>                 ReceiveEndpoint = new Action<string, string, Action<string, string, IRabbitMqReceiveEndpointConfigurator>, IBusRegistrationContext, IRabbitMqBusFactoryConfigurator>((exchangeName, queueName, preConfigure, ctx, cfg) =>
>                 {
>                     cfg.ReceiveEndpoint(queueName, e =>
>                     {
>                         preConfigure?.Invoke(exchangeName, queueName, e);
>                         e.ConfigureConsumer<OrderStateChangedConsumer>(ctx);
>                     });
>                 })
>             });
> 
>             Serilog.Log.Information($"    - PreConfigure AbpMassTransitRabbitMqOptions ExchangeName => {RabbitMqQueues.ExchangeOrderStateChanged}, with QueueName => {RabbitMqQueues.QueueOrderStateChanged}, with Consumer => {nameof(OrderStateChangedConsumer)}, with Message => {nameof(OrderStateChanged)}");
> 
>         }));
>         Serilog.Log.Debug(" - PreConfigure Services AbpMassTransitRabbitMqOptions.");
>     }
> ```
> 
> In another applicacion, i configured the connection name like that... is a very old version of the library Masstransit 5.5.6.0
> 
> ```
>                     _bus = MassTransit.Bus.Factory.CreateUsingRabbitMq(x =>
>                     {
>                         x.UseLog4Net();
> 
>                         //// IRabbitMqHost host = x.Host(new Uri(rabbitMqHostUri), connectionName, h =>                        
>                         x.Host(new Uri(rabbitMqHostUri), connectionName, h =>
>                         {
>                             h.Username(rabbitMqHostUsername);
>                             h.Password(rabbitMqHostPassword);                            
>                         });
>                         ....
> ```
> 
> Thank you very much, it has made my use of masstransit / rabbitmq with abp much faster.

Sorry, not support yet . Will support next version.

**Comment by cocosip** [comment]
Sorry , not support yet. Will support next version

**Comment by cocosip** [comment]
``` json
{
  "MassTransitOptions": {
    "Prefix": "SharpAbp",
    "Provider": "RabbitMQ",
    "WaitUntilStarted": true,
    "StartTimeoutMilliSeconds": 30000,
    "StopTimeoutMilliSeconds": 1000,
    "RabbitMqOptions": {
      "Host": "localhost",
      "Port": 5672,
      "VirtualHost": "/",
      "Username": "guest",
      "Password": "guest",
      "ConnectionName": "xxx",
      "UseSsl": false,
      "UseCluster": false,
      "ClusterNodes": [],
      "DefaultQueuePrefix": "demo1",
      "DefaultConcurrentMessageLimit": 3,
      "DefaultPrefetchCount": 4,
      "DefaultDurable": true,
      "DefaultAutoDelete": false,
      "DefaultExchangeType": "fanout"
    }
  }
}
```
You can configure `ConnectionName` by appsettings.json

**Comment by genoher** [comment]
Thank you very much for the quick response. I appreciate it a lot.
I'll be attentive and check the next version. Thank you so much.

**Comment by genoher** [comment]
You are awesome. I see that you release the new versiones 6 hours ago ;) Thanks
