### ISSUE TITLE
Distributed Events Implementation with Masstransit

### ISSUE THREAD

**Issue by lommez** [cocosip/sharp-abp#46]
Hi
Do you have any plans to implement the DistributedEventBusBase class, using the Masstransit library?

**Comment by cocosip** [comment]
I will adapt to use MassTransit as the DistributedEventBus  later

**Comment by lommez** [comment]
@cocosip 
Very good to know!!
Do you have any idea when to start adapt that?

**Comment by cocosip** [comment]
MassTransit Abp EventBus [Sample](https://github.com/cocosip/sharp-abp/blob/dev/samples/eventbus-sample/src/MassTransitEventBusSample/MassTransitEventBusSampleModule.cs)

**Comment by lommez** [comment]
Hi @cocosip!
Thank you very much, it is working perfectly.
I created a branch of the repository to try to implement a version to use Azure ServiceBus as a broker together with Masstransit.
It is still at an early stage.
But if you have any plans or some work already underway regarding this, maybe we could do it together.
Thanks
