### ISSUE TITLE
有点没看懂freesql的扩展。

### ISSUE THREAD

**Issue by ccnetcore** [cocosip/sharp-abp#49]
有点没看懂freesql的扩展。

**Comment by ccnetcore** [comment]
是正在进行嘛？我看很多内容还没有补充

**Comment by cocosip** [comment]
集成方式与ABP Dapper的集成方式相同。ABP的 UnitOfWork与 FreeSql的是有差异的，如果要FreeSql 完全接管 ABP EF的 UnitOfWork 改动量太大了。所以采用轻量级的集成，通过获取 IDbConnection,  FreeSql 自带的针对 IDbConnection的扩展方法实现
